stages:
- build

variables:
  BUILD_VERSION: "1.0.15"
  NUGET_APIKEY: "0F2DB634-4E83-4659-8068-EF552DDC4072"
  NUGET_SERVER: "http://nuget.boyu66.net"

before_script:
  - if "%CI_BUILD_REF_NAME%" == "master"  set BUILD_TARGET=
  - if "%CI_BUILD_REF_NAME%" == "dev" set BUILD_TARGET=-BETA
  - set

develop_build_job:
  stage: build
  only:
  - dev
  script:
  - c:\Multi-Runner\nuget.exe restore
  - '"c:\Program Files (x86)\MSBuild\14.0\Bin\amd64\MSBuild.exe" /p:Configuration=Release /p:Platform="Any CPU" /p:VersionAssembly=%BUILD_VERSION% DAOLibrary.sln'
  - c:\Multi-Runner\nuget.exe pack DAOLibrary\DAOLibrary.csproj -Properties Configuration=Release -Version %BUILD_VERSION%%BUILD_TARGET%
  - c:\Multi-Runner\nuget.exe push DAOLibrary.%BUILD_VERSION%%BUILD_TARGET%.nupkg -ApiKey %NUGET_APIKEY% -Source %NUGET_SERVER%
