stages:
    - build
#    - test
#    - deploy
#    - push

variables:
  BUILD_VERSION: 1.0.0.0

before_script:
#  - 'C:\Nuget\nuget.exe restore MVCApp.sln'

build_job:
    stage: build
    script:
#        - set
#        - TIME /t > %TIME:~0,2%%TIME:~3,2%.txt
        - echo %CD%
        - echo %CI_PIPELINE_ID%
#        - cd DAOLibrary
        - c:\Multi-Runner\nuget restore
        - echo %CD%
        -  '"c:\Program Files (x86)\MSBuild\14.0\Bin\amd64\MSBuild.exe" /p: /p:Configuration=Release /p:Platform="Any CPU" /p:outputpath=build_output DAOLibrary.sln'
        - md artifacts
        - xcopy /e /i DAOLibrary\build_output\DAOLibrary artifacts\build
    artifacts:
      name: daolibrary-binary
      when: on_success
      expire_in: 12 week
      paths:
        - artifacts/


#deploy_IIS_job:
#    stage: deploy
#    script:
#        - C:\Windows\System32\inetsrv\appcmd.exe stop apppool zues
#        - rd /s /q D:\Apps\Zeus
#        - xcopy /e /i artifacts\SIT D:\Apps\Zeus
#        - C:\Windows\System32\inetsrv\appcmd.exe start apppool zues
#        
#deploy_DOCKER_job:
#    stage: push
#    script:
#        - docker build -t runner/zeus:latest -t runner/zeus:%DATE:~6,4%%DATE:~0,2%%DATE:~3,2% d:\Apps\Zeus