stages:
- build

variables:
  BUILD_VERSION: "1.0.11"
  NUGET_APIKEY: "0F2DB634-4E83-4659-8068-EF552DDC4072"
  NUGET_SERVER: "http://172.20.5.15/nugetServer/"

before_script:
- set

develop_build_job:
  stage: build
  only:
  - dev
  script:
  - c:\Multi-Runner\nuget.exe restore
  - '"c:\Program Files (x86)\MSBuild\14.0\Bin\amd64\MSBuild.exe" /p:Configuration=Release /p:Platform="Any CPU" /p:VersionAssembly=%BUILD_VERSION% DAOLibrary.sln'
  - c:\Multi-Runner\nuget.exe pack DAOLibrary\DAOLibrary.csproj -Properties Configuration=Release -Version %BUILD_VERSION%
  - c:\Multi-Runner\nuget.exe push DAOLibrary.%BUILD_VERSION%.nupkg -ApiKey %NUGET_APIKEY% -Source %NUGET_SERVER%
